# comment 
trusted-users = colawithsauce
substituters = https://mirrors.ustc.edu.cn/nix-channels/store https://cache.nixos.org/
extra-nix-path = nixpkgs=flake:nixpkgs
experimental-features = nix-command flakes
bash-prompt-prefix = (nix:$name)\040
auto-optimise-store = true
build-users-group = nixbld
