preload = ~/Pictures/Monet1.jpg
preload = ~/Pictures/Monet2.jpg
preload = ~/Pictures/Monet3.jpg
preload = ~/Pictures/Monet4.jpg
preload = ~/Pictures/vanGogh1.jpg
preload = ~/Pictures/linux-dark.png
wallpaper = eDP-1,~/Pictures/linux-dark.png

ipc = off
