# preload = ~/Pictures/Monet1.jpg
# preload = ~/Pictures/Monet2.jpg
# preload = ~/Pictures/Monet3.jpg
# preload = ~/Pictures/Monet4.jpg
# preload = ~/Pictures/cogecha1.jpg
# preload = ~/Pictures/cogecha2.jpg
# preload = ~/Pictures/cogecha3.jpg
# preload = ~/Pictures/cogecha4.jpg
# preload = ~/Pictures/vanGogh1.jpg
preload = ~/dotfiles/assets/Pictures/cogecha2.jpg
preload = ~/dotfiles/assets/Pictures/anime_girls1.jpg
wallpaper = eDP-1,~/dotfiles/assets/Pictures/anime_girls1.jpg

ipc = off
