# preload = ~/dotfiles/assets/Pictures/Monet1.jpg
#preload = ~/dotfiles/assets/Pictures/Monet2.jpg
#preload = ~/dotfiles/assets/Pictures/Monet3.jpg
#preload = ~/dotfiles/assets/Pictures/Monet4.jpg
#preload = ~/dotfiles/assets/Pictures/cogecha1.jpg
#preload = ~/dotfiles/assets/Pictures/cogecha2.jpg
#preload = ~/dotfiles/assets/Pictures/cogecha3.jpg
#preload = ~/dotfiles/assets/Pictures/cogecha4.jpg
#preload = ~/dotfiles/assets/Pictures/vanGogh1.jpg
#preload = ~/dotfiles/assets/Pictures/anime_girls1.jpg
preload = ~/dotfiles/assets/Pictures/nature.jpg
# preload = ~/dotfiles/assets/Pictures/bluesky.jpg
# preload = ~/dotfiles/assets/Pictures/Persona3.png
# preload = ~/dotfiles/assets/Pictures/persona5.png
# preload = ~/dotfiles/assets/Pictures/grass.jpg
# wallpaper = ,contain:~/dotfiles/assets/Pictures/bluesky.jpg
wallpaper = ,contain:~/dotfiles/assets/Pictures/nature.jpg

ipc = off
